### PR TITLE
#8794 - fix showForConditionalField for 0 value in parent

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Fix for https://github.com/mautic/mautic/pull/8794
- creat parent radio button with values 0 / 1 - optin to newsletter for example
- condition (children) don't save value to contact profile because there was in_array in strict mode and 0 / 1 is processed as INT
- condition don't save value If you use any option because 0 is was consider as not existed value

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Nice tests. Thanks! 👍

**Comment by escopecz** [comment]
@kuzmany it fails some other tests. I run the CI once more to see if it's not temporary, but it happened again.

**Comment by kuzmany** [comment]
@escopecz working on unit tests
Can you please merge 3.3 to your branch? 
There is one unit test failed and fixed by https://github.com/mautic/mautic/pull/9703

**Comment by kuzmany** [comment]
@escopecz unit tests passed. Can you review it?

**Review by escopecz — APPROVED** [review]

**Pull request merged**
